src/CashFlow.MVC/Controllers/SheetController.cs
using CashFlow.Application.DTOs;
using CashFlow.Application.Interfaces;
using CashFlow.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace CashFlow.MVC.Controllers
{
    [Authorize]
    public class SheetController : Controller
    {
        private readonly ISheetService _sheetService;
        private readonly UserManager<User> _userManager;
        private readonly IFinancialEntryService _entryService;
        private readonly IFinancialExpenseService _expenseService;

        public SheetController(ISheetService sheetService, UserManager<User> userManager, IFinancialEntryService entryService, IFinancialExpenseService expenseService)
        {
            _sheetService = sheetService;
            _userManager = userManager;
            _entryService = entryService;
            _expenseService = expenseService;
        }


        public async Task<IActionResult> Index()
        {

            var sheets = await _sheetService.GetAllAsync();


            return View(sheets);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var sheet = await _sheetService.GetByIdAsync(id);

            if (sheet == null)
            {
                return NotFound();
            }

            var entries = await _entryService.GetAllAsync(id);

            var expenses = await _expenseService.GetAllAsync(id);

            var viewModel = new SheetDetailsViewModel
            {
                Sheet = sheet,
                Entries = entries,
                Expenses = expenses
            };

            return View(viewModel);
        }


        public async Task<IActionResult> Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SheetDTO sheetDTO)
        {
            if (ModelState.IsValid)
            {

                await _sheetService.CreateSheetAsync(sheetDTO);

                return RedirectToAction(nameof(Index));
            }

            return View(sheetDTO);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var sheet = await _sheetService.GetByIdAsync(id);
            return View(sheet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name")] SheetDTO sheetDTO)
        {
            if (ModelState.IsValid)
            {
                await _sheetService.UpdateByIdAsync(id, sheetDTO);
                return RedirectToAction(nameof(Index));
            }

            return View(sheetDTO);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            return View(await _sheetService.GetByIdAsync(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (ModelState.IsValid)
            {
                await _sheetService.DeleteByIdAsync(id);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

src/CashFlow.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle Financeiro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Teste.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light text-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Sheet" asp-action="Index">
                    <i class="bi bi-wallet"></i> Controle Financeiro
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
@*                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Sheet" asp-action="Index">Sheet</a>
                        </li> *@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer -->
    <footer class="border-top footer text-muted bg-light mt-5">
        <div class="container">
            &copy; 2023 - Controle Financeiro - <a asp-area="" asp-controller="Sheet" asp-action="Index">Privacy</a> | Desenvolvido por Aldruin Bonfim de Lima Souza
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>